- docs/manipulating_plots.md
- src/api.jl
- test/api.jl
This is the changeset that should fix #23.
It ended up being quite a bit more complicated than I initially expected as the semantics of plotly.js are a bit complicated.
I have tests for the cases I could think of and the tests show that we do match semantics on those cases.
cc @tbreloff
> Matching plotly.js semantics in restyle!

- src/json.jl
Hi @spencerlyon2 ,
I'd like to be able to use your PlotlyJS types with string interpolation so this PR simply adds a `print` method so that we can do things like:
~~~julia
julia> using PlotlyJS
julia> t1 = scatter(;x=[1, 2, 3, 4, 5],
y=[1, 6, 3, 6, 1],
mode="markers+text",
name="Team A",
text=["A-1", "A-2", "A-3", "A-4", "A-5"],
textposition="top center",
textfont_family="Raleway, sans-serif",
marker_size=12)
scatter with fields marker, mode, name, text, textfont, textposition, x, and y
julia> "hello $t1"
"hello {\"type\":\"scatter\",\"y\":[1,6,3,6,1],\"text\":[\"A-1\",\"A-2\",\"A-3\",\"A-4\",\"A-5\"],\"textfont\":{\"family\":\"Raleway, sans-serif\"},\"name\":\"Team A\",\"x\":[1,2,3,4,5],\"textposition\":\"top center\",\"mode\":\"markers+text\",\"marker\":{\"size\":12}}"
~~~ 
What do you …
> Let string interpolation stringify to JSON format

- src/json.jl
My previous PR ( #38 ) allowed for string interpolation of basic PlotlyJS types including GenericTrace. In addition to those, we also need vectors of generic traces. This PR completes that.
I use this in Pages.jl for sending JS commands from Julia to a browser, e.g.
~~~julia
n = 10
trace1 = scatter(;x = 1:n, y = rand(n))
trace2 = scatter(;x = 1:n, y = rand(n))
data = [trace1, trace2]
layout = Layout(;title = "Create a new <div> and plot an array of traces",
width = 600,
height = 300
)
id = "Plot2"
add_div(id)
Pages.broadcast("script","""Plotly.newPlot("$(id)",$(data),$(layout));""")
~~~
Without this PR, I'd need to do this instead:
~~~julia
n = 10
trace1 = scatter(;x = 1:n, y = rand(n))
trace2 = scatter(;x = 1:n, y = rand(n))
data = [trace1, trace2]
layout = Layout(;title = "Create a new …
> JSON for vectors of traces.

- src/json.jl
According to https://github.com/JuliaLang/JSON.jl/commit/bd1eb8a7e4c5e1c3cc42d912bcdf41a0603c0527
Possibly fixes https://github.com/spencerlyon2/PlotlyJS.jl/issues/46
> Update use of JSON.colon to JSON.separator

- src/api.jl
- src/json.jl
- src/traces_layouts.jl
- test/traces.jl
This makes it so `JSON._print(..., hf::HasFields, ...) = JSON._print(..., hf.fields, ...)`  instead of re-implementing most of the object serialization for `Shape` and `GenericTrace` types. 
Ref: https://github.com/JuliaLang/METADATA.jl/pull/5427
Is there a way to avoid overloading `JSON._print` (hinted at by @TotalVerb [here](https://github.com/JuliaLang/METADATA.jl/pull/5427#issuecomment-226982997))? I don't think defining `JSON.json` will work here for reasons described [here](https://github.com/JuliaLang/METADATA.jl/pull/5427#issuecomment-227211908)
cc @TotalVerb, @tkelman
> Remove `kind` field for GenericTrace and Shape.

- src/json.jl
Before the change, this example errored: 
```julia
using Plots
plotlyjs()
plot([Date(2016,1,1), Date(2016,2,1)], [1,2])
```
> fix dates in json

- .travis.yml
- src/PlotlyJS.jl
- src/api.jl
- src/json.jl
- src/traces_layouts.jl
This fixes deprecation warnings and errors with Julia 0.5. Getting the tests working was also the occasion for fixing two julia bugs, https://github.com/JuliaLang/julia/pull/17966 and https://github.com/JuliaLang/julia/pull/17968. This won't pass tests on 0.5 until those are backported, but the tests do pass for me locally.
> Fixes for Julia 0.5

- REQUIRE
- src/json.jl
In JSON v0.7.0 and beyond, overloads of _print are deprecated in favour of overloading the simpler lower function.
The new JSON tag is not yet merged; see JuliaLang/METADATA.jl#5988. I'll ping you when it is.
> Extend `JSON.lower` instead of `JSON.print`

- src/PlotlyJS.jl
- src/displays/juno.jl
- src/styles.jl
If the user has not overridden the empty default style, we use gadfly_dark in Juno.
Modifying the plot feels unclean to me, so there may be a nicer way to do that – but I don't think it should cause issues if not.
> Use dark theme in Juno

- src/PlotlyJS.jl
- src/displays/ijulia.jl
See https://github.com/JuliaLang/Interact.jl/issues/115 for more context
Tl;dr: on page refresh the Jupyter front end clears all registered comms, so the `_ijulia_eval_comm` held by PlotlyJS becomes stale. This change ensures a new global Comm is created every time `JupiterDisplay` is called, which stops the old Comm from becoming stale on page refresh.
> Simpler way to fix use with Interact in IJulia on page refresh

- src/display.jl
- src/savefig.jl
* `readall` has been renamed to `readstring` on Julia 0.6
* Enables setting a default js loading preference. Doesn't change current behaviour but enables having plotly.js javascript file loaded via embed or from cdn by default.
InteractNext will set `js_default` to :embed (using Requires.jl - [code here](https://github.com/JuliaGizmos/InteractNext.jl/blob/plotly-js-default/src/setup.jl#L19)) which will make it easier to support PlotlyJS in Mux, Blink, and Juno.
> Readall rename and Js loading default

- docs/styles.md
- src/styles.jl
- test/styles.jl
Fix typo in `length(Cycler)` and use `mod1()` in `getindex()`.
> Tiny Cycler fixes

- src/display.jl
- src/displays/webio.jl
This defines a `WebIO.render` method for PlotlyJS plot objects, so that they work out of the box withing a InteractBase GUI. The current solution involves a nasty hack setting the PlotlyJS default from within InteractBase so that it embeds the javascript and I'd like to get rid of that hack (it's also horrible performance-wise). 
This can go as soon as the PlotlyWebIO story is complete, but I think it's a good stop-gap solution till then, as I'm really not comfortable with [this code](https://github.com/piever/InteractBase.jl/blob/master/src/package_support.jl).
> webio integration

- .travis.yml
- REQUIRE
- deps/find_attr_groups.jl
- deps/make_schema_docs.jl
- docs/basics.md
- docs/build_example_docs.jl
- docs/building_traces_layouts.md
- src/PlotlyJS.jl
- src/display.jl
- src/displays/electron.jl
- src/displays/ijulia.jl
Hi!
Here I fixed issues with `Nullable`, `readstring`, `AbstractDictionary`, `Markdown` and `reexport`.
This version still doesn't work on Julia 0.7 because of problems in [Blink.jl](https://github.com/JunoLab/Blink.jl/pull/133), which, if I understood correctly, goes further to [WebIO](https://github.com/JuliaGizmos/WebIO.jl/pull/157). Though now it at least can be built.
> Fixes for Julia v0.7

- src/PlotlyJS.jl
It's used on [this line](https://github.com/sglyon/PlotlyJS.jl/blob/2fb2f20e40cd79777625f31f6c6fadc3b0bac14c/src/display.jl#L28)
> Import html_body from PlotlyBase

- src/display.jl
Related to Issue [223](https://github.com/sglyon/PlotlyJS.jl/issues/223). Enables using of dynamical plotting with `extendtraces!`
> ENH: enables dynamical plotting when run in terminal or atom

- src/display.jl
Fixes https://github.com/sglyon/PlotlyJS.jl/issues/229.
Should probably not be merged yet (or at least not released).
> use webio for Juno integration

- src/display.jl
There's still an issue with JupyterLab because the bundle tries to access the WebIO global (which doesn't exist in JupyterLab). This is a non-issue for simply displaying plots, but is an issue for interactive plots. I'll open a separate issue for the JupyterLab problem.
> Add fix for WebIO 0.8.0+.

- Project.toml
- src/display.jl
This will not pass on CI until https://github.com/JuliaRegistries/General/pull/1473 is merged.
This fixes #278.
> Update to latest WebIO.

- src/display.jl
The previous behavior was to rescale the plot contents to fit the default window size on creation.
This update modifies the window dimensions to fit the plot contents.
Issue: 314
> Modify plot window dimensions on creation to fit plot contents

- .github/workflows/artifacts.yml
- .github/workflows/deploy_docs.yml
- Artifacts.toml
- Project.toml
- README.md
- deps/find_attr_groups.jl
- deps/generate_artifacts.jl
- deps/make_schema_docs.jl
This pull request comprises the generation of the plotly-artifacts using GitHub Actions. We can (for now) manually run the action "artifacts" to update (or generate) the tarball "plotly-artifacts.tar.gz" which is available as a release. The Artifacts.toml file is then updated automatically.
As a side effect, this pull request resolves #369 and #370 .
Please feel free to propose further changes!  👍 
EDIT: Unfortunately, the Documenter workflow is currently broken since the update of the hash in the file Artifact.toml happens in a separate commit.
> Generate artifacts using gh-actions

- docs/src/manipulating_plots.md
> Corect wrong link to plotly javascript documentation

- Project.toml
This is a short term remedy for #440, once WebIO fixes this one way or another this should be revisited.
Fix #440
> add upper bound for WebIO compat entry

- docs/src/manipulating_plots.md
replace `vect` syntax by `vcat` syntax for generation of subplots as the vect syntax has been removed
> use vcat syntax for generation of subplots

- src/PlotlyJS.jl
Starting from Julia v1.10, using PlotlyJS.jl as a dependency of any other package causes the precompilation of this other package to be stuck, as explained in https://github.com/JuliaLang/julia/issues/50505. This PR fixes that.
The root cause of the issue was https://github.com/JuliaLang/julia/issues/48506. To be honest, I'm not sure I understand why the behavior of the `__init__` function of PlotlyJS should livelock the precompilation of *other* packages... but I was inspired by https://github.com/JuliaDebug/Cthulhu.jl/pull/343/files and https://github.com/JuliaImages/ImageView.jl/pull/279/files, which targeted similar issues, for this PR.
> Fix precompilation of packages depending on PlotlyJS

- .github/workflows/artifacts.yml
- .gitignore
- deps/generate_artifacts.jl
- deps/plotly_cdn_version.jl
- src/PlotlyJS.jl
- src/display.jl
- test/runtests.jl
This PR makes sure that the same version of the plotlyjs web asset is used for all imports: through artifact or through CDN.
This also adds `_js_version` and `_js_path` as public API: this means other packages can depend on PlotlyJS.jl to get the plotly.min.js asset. Used in https://github.com/JuliaPlots/Plots.jl/pull/4862
> Use the same plotlyjs version number for all imports

- ext/IJuliaExt.jl
> Fix for using IJulia with Julia 1.11.1 and the new Memory array types.

- docs/src/manipulating_plots.md
- src/display.jl
- src/kaleido.jl
This PR does 2 things:
* cleanup `savefig()`: combine docstring from all 3 versions, streamline keyword argument passing using `kwargs...`
* add `plotlyjs` and `plotly_version` keyword arguments to `savefig()` to control which *plotly.js* Kaleido would be using to generate the figures.
This is to allow using more recent versions of *plotly.js* than the one provided by the *PlotlyJS.jl* (the current one, 2.3.0, is more than a year old).
I have also regenerated the *plotly.js* artifact using version *2.35.2*.
I can provide the file, or the maintainers can run `generate_artifacts.jl` themselves.
See also [comment for PlotlyBase.jl#106](https://github.com/sglyon/PlotlyBase.jl/pull/106#issuecomment-2534636986)
> Enhance savefig()

- .github/workflows/TagBot.yml
- .github/workflows/deploy_docs.yml
Revise the GitHub Actions workflow for triggering Documenter builds to be slightly more conventional.
> Further update to workflows for documentation deployment
